// Buscar produtos
GET http://localhost:5005/produtos

###

// Criar um produto
POST http://localhost:5005/produto
Content-Type: application/json

{
    "id": 235,
    "nome": "Produto 2",
    "preco": 350,
    "off": 17
}

###

// Buscar produto por id
GET http://localhost:5005/produto/234
###
// atualizar
PUT http://localhost:5005/produto/234
Content-Type: application/json

{
    "nome": "Produto novo"
}

###

DELETE http://localhost:5005/produto/234
###
DELETE http://localhost:5005/produto